version: '2.0'

services:  
  app:
    image: aurora/internetnl:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    network_mode: host
    environment:
      - DB_HOST=127.0.0.1
    #dns: 127.0.0.1
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW
    #volumes:
      #- /tmp/run/mysqld:/var/run/mysqld
    #ports:
    #- "8080:8080"
    restart: on-failure
    depends_on:
      - redis
      - rabbitmq
      - mysql

  redis:
    network_mode: host
    image: redis:alpine

  rabbitmq:
    network_mode: host
    image: rabbitmq:alpine

  mysql:
    network_mode: host
    image: aurora/mysql:latest
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=internetnl
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=internetnl_db1
    volumes:
      - my-datavolume:/tmp/lib/mysql
      #- /tmp/run/mysqld:/var/run/mysqld
volumes:
  my-datavolume:
