version: '2.0'

services:  
  app:
    image: nlnetlabs/internetnl:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    network_mode: host
    dns: 127.0.0.1
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - rabbitmq
      - postgres

  redis:
    network_mode: host
    image: redis:alpine

  rabbitmq:
    network_mode: host
    image: rabbitmq:alpine

  postgres:
    network_mode: host
    image: mysql:latest
    environment:
      - MYSQL_USER=internetnl
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=internetnl_db1
    volumes:
      - my-datavolume:/tmp/lib/mysql
volumes:
  my-datavolume:
