version: '2.0'
services:
  app:
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/app

      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig

      # Forwarding the socket is optional, but lets docker work inside the container if you install the Docker CLI.
      # See the docker-in-docker-compose definition for details on how to install it.
      - /var/run/docker.sock:/var/run/docker.sock 

    # Overrides default command so things don't shut down after the process ends - useful for debugging
    command: /app/docker/setup-dev-env.sh
